typedef unsigned char Uint8;
typedef unsigned short Uint16; 
typedef unsigned long Uint32;

//background tiles
#include "graphic/owmap.c"
#include "graphic/menu.c"
#include "graphic/cave.c"
#include "graphic/grass.c"
#include "graphic/forest.c"
#include "graphic/castle.c"
#include "graphic/desert.c"
#include "graphic/icave.c"
#include "graphic/ecave.c"
#include "graphic/marsh.c"
#include "graphic/mcave.c"
#include "graphic/river.c"
#include "graphic/sshrine.c"
#include "graphic/temple.c"
#include "graphic/tower.c"
#include "graphic/volcano.c"
#include "graphic/water.c"
#include "graphic/waterfall.c"

//maps
#include "graphic/bMap.c"
#include "graphic/cname.c"
#include "graphic/cselect.c"
#include "graphic/title.c"

//sprites
#include "graphic/cursor.c"
#include "graphic/font.c"
#include "graphic/owsprite.c"
#include "graphic/bsprite.c"
#include "graphic/small0.c"
#include "graphic/small1.c"
#include "graphic/small2.c"
#include "graphic/small3.c"
#include "graphic/small4.c"
#include "graphic/small5.c"
#include "graphic/small6.c"
#include "graphic/small7.c"
#include "graphic/small8.c"
#include "graphic/small9.c"
#include "graphic/small10.c"
#include "graphic/small11.c"
#include "graphic/small12.c"
#include "graphic/large0.c"
#include "graphic/large1.c"
#include "graphic/large2.c"
#include "graphic/large3.c"
#include "graphic/large4.c"
#include "graphic/large5.c"
#include "graphic/large6.c"
#include "graphic/large7.c"
#include "graphic/large8.c"
#include "graphic/large9.c"
#include "graphic/large10.c"
#include "graphic/large11.c"
#include "graphic/large12.c"
